[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes = [5159]


[invariant]
# runs = 256
depth = 100

# See more config options https://github.com/foundry-rs/foundry/tree/master/config